import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cfg = window.KG_RENTALS || {};
const ready = Boolean(cfg.supabaseUrl && cfg.supabaseAnonKey);
const db = ready ? createClient(cfg.supabaseUrl, cfg.supabaseAnonKey) : null;
const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast = s => { $('#toast').textContent=s; $('#toast').style.display='block'; setTimeout(()=>$('#toast').style.display='none',5000); };
let user=null, listings=[], selected=null, tab='tenant';
function requireSetup(){if(!ready){toast('Online accounts are being set up. Please contact KG Realty for now.');return false}return true}
async function currentUser(){if(!db)return; const {data}=await db.auth.getUser();user=data.user;$('#accountButton').textContent=user?'My dashboard':'Sign in';}
async function loadListings(){
  if(!db){$('#listingGrid').innerHTML='<div class="empty"><h3>Rental listings are coming soon.</h3><p>Contact KG Realty to ask about available homes.</p><a class="button" href="mailto:keremgorgulu@gmail.com?subject=Rental%20availability">Ask about rentals</a></div>';$('#listingCount').textContent='Listings coming soon';return}
  const {data,error}=await db.from('rental_listings').select('id,city,address,rent,beds,baths,sqft,description,photo_url,available_on').eq('status','published').order('created_at',{ascending:false});
  if(error){toast('Listings could not be loaded.');return}listings=data||[];renderListings();
}
function renderListings(){const q=$('#search').value.trim().toLowerCase(), max=Number($('#maxRent').value)||Infinity,beds=Number($('#beds').value);const results=listings.filter(x=>(x.city+' '+x.address).toLowerCase().includes(q)&&Number(x.rent)<=max&&Number(x.beds)>=beds);$('#listingCount').textContent=`${results.length} home${results.length===1?'':'s'}`;$('#listingGrid').innerHTML=results.length?results.map(x=>`<article class="card"><div class="card-image">${x.photo_url?`<img src="${esc(x.photo_url)}" alt="Exterior of rental home" loading="lazy">`:'⌂'}</div><div class="card-body"><p class="price">$${Number(x.rent).toLocaleString()}/mo</p><h3>${esc(x.address)}</h3><p class="meta">${esc(x.city)}, TX · ${esc(x.beds)} beds · ${esc(x.baths)} baths${x.sqft?' · '+esc(x.sqft)+' sq ft':''}</p><button class="button detail" data-id="${esc(x.id)}" type="button">View home</button></div></article>`).join(''):'<div class="empty"><h3>No homes match these filters.</h3><p>Try another city, price or bedroom count. New listings will appear here when approved.</p></div>'}
$('#filters').addEventListener('submit',e=>{e.preventDefault();renderListings()});
$('#listingGrid').addEventListener('click',e=>{let b=e.target.closest('.detail');if(b)showDetail(b.dataset.id)});
function showDetail(id){selected=listings.find(x=>x.id===id);if(!selected)return;$('#detailTitle').textContent=selected.address;$('#detailContent').innerHTML=`<p class="price">$${Number(selected.rent).toLocaleString()}/month</p><p>${esc(selected.city)}, Texas · ${esc(selected.beds)} bedrooms · ${esc(selected.baths)} bathrooms</p><p>${esc(selected.description)}</p><p class="fine">Applications are reviewed by the listing contact using written screening criteria. No screening reports are collected on this site.</p><button class="button" id="applyNow" type="button">Apply for this home</button>`;$('#detailDialog').showModal();$('#applyNow').onclick=()=>{ $('#detailDialog').close();apply(selected.id);}}
async function signIn(){if(!requireSetup())return;await currentUser();if(user)return dashboard();$('#authDialog').showModal()}
$('#accountButton').onclick=signIn;$('#ownerStart').onclick=async()=>{tab='owner';await signIn()};
$('#authForm').onsubmit=async e=>{e.preventDefault();if(!requireSetup())return;let email=new FormData(e.target).get('email');const {error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname}});$('#authStatus').textContent=error?error.message:'Check your inbox for your sign-in link.'};
if(db)db.auth.onAuthStateChange(async()=>{await currentUser();if(user&&$('#authDialog').open){$('#authDialog').close();dashboard()}});
async function apply(id){if(!requireSetup())return;await currentUser();if(!user){toast('Sign in first, then open the home again to apply.');return $('#authDialog').showModal()}selected=listings.find(x=>x.id===id);tab='tenant';dashboard();setTimeout(()=>$('#applicationPanel')?.scrollIntoView({block:'nearest'}),50)}
async function dashboard(){if(!user)return signIn();$('#dashboardDialog').showModal();renderDashboard()}
async function renderDashboard(){const root=$('#dashboardContent');root.innerHTML='<p>Loading your account…</p>';const [{data:mine,error:le},{data:apps,error:ae}]=await Promise.all([db.from('rental_listings').select('*').eq('owner_id',user.id).order('created_at',{ascending:false}),db.from('rental_applications').select('*,rental_listings(address,city,owner_id)').order('created_at',{ascending:false})]);if(le||ae){root.textContent='Your account could not be loaded. Please try again.';return}const own=mine||[], applications=apps||[];root.innerHTML=`<p class="fine">Signed in as ${esc(user.email)} · <button id="signOut" type="button">Sign out</button></p><div class="tabs"><button data-tab="tenant" class="${tab==='tenant'?'active':''}">My applications</button><button data-tab="owner" class="${tab==='owner'?'active':''}">My listings</button><button data-tab="messages" class="${tab==='messages'?'active':''}">Messages</button></div><div id="tabContent"></div>`;$('#signOut').onclick=async()=>{await db.auth.signOut();user=null;$('#dashboardDialog').close();await currentUser()};root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;root.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));drawTab()});
function drawTab(){const box=$('#tabContent');if(tab==='owner'){box.innerHTML=`<div class="notice">Listings go live after KG Realty reviews the property and brokerage terms. Online listing payment is not enabled yet.</div><h3>Your listings</h3>${own.length?own.map(x=>`<div class="row"><div><strong>${esc(x.address)}</strong><p>${esc(x.city)} · $${Number(x.rent).toLocaleString()}/mo</p></div><span class="pill">${esc(x.status)}</span></div>`).join(''):'<p>No listings submitted yet.</p>'}<h3>Submit a rental home</h3><form id="listingForm" class="stack"><label>Street address<input name="address" maxlength="160" required></label><label>City<input name="city" maxlength="80" required></label><label>Monthly rent ($)<input name="rent" type="number" min="1" max="100000" required></label><label>Bedrooms<input name="beds" type="number" min="0" max="30" required></label><label>Bathrooms<input name="baths" type="number" min="0" max="30" step="0.5" required></label><label>Size (sq ft)<input name="sqft" type="number" min="1" max="100000"></label><label>Home details<textarea name="description" maxlength="3000" required></textarea></label><label>Photo URL (optional, HTTPS only)<input name="photo_url" type="url" placeholder="https://..."></label><button class="button">Submit for review</button></form><h3>Applications to your homes</h3>${applications.filter(a=>own.some(x=>x.id===a.listing_id)).map(a=>`<div class="row"><div><strong>${esc(a.full_name)}</strong><p>${esc(a.rental_listings?.address)} · ${esc(a.email)} · ${esc(a.message)}</p></div><select class="application-status" data-id="${esc(a.id)}" aria-label="Application status"><option ${a.status==='submitted'?'selected':''}>submitted</option><option ${a.status==='reviewing'?'selected':''}>reviewing</option><option ${a.status==='approved'?'selected':''}>approved</option><option ${a.status==='declined'?'selected':''}>declined</option></select></div>`).join('')||'<p>No applications yet.</p>'}`;$('#listingForm').onsubmit=submitListing;box.querySelectorAll('.application-status').forEach(s=>s.onchange=async()=>{const {error}=await db.from('rental_applications').update({status:s.value}).eq('id',s.dataset.id);toast(error?error.message:'Status saved. Send any required notices separately.');if(!error)renderDashboard()});}
else if(tab==='tenant'){box.innerHTML=`<h3>My applications</h3>${applications.filter(a=>a.applicant_id===user.id).map(a=>`<div class="row"><div><strong>${esc(a.rental_listings?.address)}</strong><p>${esc(a.rental_listings?.city)} · submitted ${new Date(a.created_at).toLocaleDateString()}</p></div><span class="pill">${esc(a.status)}</span></div>`).join('')||'<p>You have no applications yet. Browse homes and select Apply.</p>'}${selected?`<div id="applicationPanel"><h3>Apply for ${esc(selected.address)}</h3><p class="fine">Share only contact details and an introduction. Screening documents and payments are handled by an approved provider.</p><form id="applyForm" class="stack"><label>Full name<input name="full_name" maxlength="120" required></label><label>Contact email<input name="email" type="email" value="${esc(user.email)}" required></label><label>Phone<input name="phone" type="tel" maxlength="30" required></label><label>Message to listing contact<textarea name="message" maxlength="2000" required></textarea></label><button class="button">Submit application</button></form></div>`:''}${cfg.rentPortalUrl?`<p><a class="button" href="${esc(cfg.rentPortalUrl)}" target="_blank" rel="noopener noreferrer">Pay rent in secure portal ↗</a></p>`:''}`;if(selected)$('#applyForm').onsubmit=submitApplication;}
else{box.innerHTML='<h3>Conversations</h3><p>Select one of your applications or listings to write a message.</p>'+applications.map(a=>`<div class="row"><div><strong>${esc(a.rental_listings?.address)}</strong><p>${esc(a.full_name)} · ${esc(a.status)}</p></div><button class="button thread" data-id="${esc(a.id)}">Open</button></div>`).join('');box.querySelectorAll('.thread').forEach(b=>b.onclick=()=>openThread(b.dataset.id));}}
async function submitListing(e){e.preventDefault();const f=new FormData(e.target),photo=String(f.get('photo_url')||'');if(photo&&!/^https:\/\//i.test(photo))return toast('Photo URLs must begin with https://');const payload={owner_id:user.id,address:f.get('address'),city:f.get('city'),rent:Number(f.get('rent')),beds:Number(f.get('beds')),baths:Number(f.get('baths')),sqft:f.get('sqft')?Number(f.get('sqft')):null,description:f.get('description'),photo_url:photo||null};const {error}=await db.from('rental_listings').insert(payload);toast(error?error.message:'Listing submitted for review.');if(!error)renderDashboard()}
async function submitApplication(e){e.preventDefault();let f=new FormData(e.target);const {error}=await db.from('rental_applications').insert({listing_id:selected.id,applicant_id:user.id,full_name:f.get('full_name'),email:f.get('email'),phone:f.get('phone'),message:f.get('message')});toast(error?error.message:'Application sent. Check your dashboard for updates.');if(!error){selected=null;renderDashboard()}}
}
async function openThread(id){const {data:messages,error}=await db.from('rental_messages').select('*').eq('application_id',id).order('created_at');if(error)return toast(error.message);$('#tabContent').innerHTML=`<h3>Conversation</h3><p><button id="backThreads" type="button">← Back to messages</button></p><div aria-live="polite">${(messages||[]).map(m=>`<div class="message"><strong>${m.sender_id===user.id?'You':'Other participant'}</strong><p>${esc(m.body)}</p><small>${new Date(m.created_at).toLocaleString()}</small></div>`).join('')||'<p>No messages yet.</p>'}</div><form id="messageForm"><label>New message<textarea name="body" maxlength="2000" required></textarea></label><button class="button">Send message</button></form><p class="fine">Never send passwords, SSNs, credit reports, or banking details in messages.</p>`;$('#backThreads').onclick=()=>renderDashboard();$('#messageForm').onsubmit=async e=>{e.preventDefault();const body=new FormData(e.target).get('body');const {error}=await db.from('rental_messages').insert({application_id:id,sender_id:user.id,body});if(error)toast(error.message);else openThread(id)}}
await currentUser();await loadListings();
